### ISSUE TITLE
Remove or relax engines in package.json

### ISSUE THREAD

**Issue by ministerofpanic** [zachbryant/parcel-resolver-tspaths#2]
Hi 👋 

I found your project after hitting similar hurdles (https://github.com/parcel-bundler/parcel/issues/202)

I'm currently using `parcel@2.0.0-beta.3.1` and `node@15.13.0`, which are incompatible with the engine requirements in your package.json.

I understand these are the versions that have been tested against, but I would like to be able to use your hard-work in my project, which I can't currently do even though I have more recent versions of the deps.

I know that I can continue to install the project with:
```
yarn config set ignore-engines true
```

But I still get the following error when running `parcel`:
```
@parcel/core: The plugin "parcel-resolver-tspaths" is not compatible with the current version of Parcel. Requires "2.0.0
-beta.2" but the current version is "2.0.0-beta.3.1".
```

Please consider relaxing the requirements (or making them minimal versions required)

**Comment by zachbryant** [comment]
Hey, thanks for pointing that out! I unintentionally made it really restrictive. I went ahead and loosened up the parcel version, which should allow for future betas/nightlies etc, as well as the node version at least 14.0.0. You should be able to upgrade to `0.0.5` now. Feel free to reopen this if you need anything else 🙂
